librsvg: Autospec creation for update from version 2.48.4 to version 2.49.0
Abraham Toriz (2):
      set example's dependencies to match project's ones
      restore two notes

Adam Reichold (3):
      Use an opaque iterator instead of manual indexing for iterating path commands.
      Replace expliciting indexing by pushing onto the coordinate vector directly when building paths.
      As PackedCommand is a single byte large, make it copy and pass it by value as Clippy suggests.

Bastien Orivel (4):
      Remove the direct phf dependency
      Update png and nalgebra
      Update nalgebra and assert_cmd
      (#577): Parse multiple fonts in font-family

Chun-wei Fan (4):
      NMake Makefiles: Support running rsvg_internals tests
      tests/test-utils.c: Fix build without PangoFT2
      NMake Makefiles: Fix linking the tests
      win32/README.txt: Mention about test dependencies

Corentin Rossignon (3):
      Add fr property inside gradient structure
      Remove some SVG1.1 gradient tests since they are not compliant of SVG2 behavior
      Add a SVG2 gradient test

Federico Mena Quintero (119):
      Bump development version to 2.49.0
      Cargo update
      Parse the "type" attribute of the style element without cssparser
      Log when an element is set in error
      ComputedValues: compute font-size before its dependent properties
      (#558): Compute cascaded font-size values correctly for relative units
      Add a NodeData::get_chars() function
      Use get_chars() instead of get_impl::<NodeChars>() throughout
      Create chars nodes in a new NodeData::new_chars() function
      Rename NodeData::new() to ::new_element()
      Turn NodeData into an enum with variants for Element and Text
      Box the Element variant to make Text nodes smaller
      Add tests/fixtures/reftests/svg2 to Makefile.am
      marker: use SpecifiedValues.set_parsed_property instead of poking at fields directly
      SpecifiedValues::with_overflow_hidden - use set_parsed_property
      SpecifiedValues: make all fields private
      Represent SpecifiedValues with an array of ParsedProperty to make it smaller
      print_sizes() - also print the size of Element
      Increase limit to 1_000_000 loaded elements
      marker: impl From<&[PathCommand]> for Segments instead of From<&PathBuilder>
      Turn a PathBuilder into an immutable Path with into_boxed_slice()
      PathBuilder: use a SmallVec while the path commands are being accumulated
      Generate ComputedValues with a macro
      ComputedValues: make all fields private; access them through functions
      SpecifiedValues::get_property - new function; use it in to_computed_values()
      Remove impl Default for SpecifiedValue
      Rename the make_computed_values macro to make_properties
      make_properties: specify all properties for ComputedValues as longhands
      make_properties: Add space for shorthand properties
      Generate ParsedProperty with the make_properties macro
      Generate PropertyId with the make_properties macro
      Use a PropertyId::is_shorthand() function instead of special-casing Marker
      ComputedValues::set_value - new function to abstract setting a computed value
      properties.rs: Use accessor functions for ComputedValues everywhere
      ComputedValues::get_value - New function; do all property accesses through this
      Generate parse_property() with the make_properties macro
      A better docstring for make_properties
      Path.iter() - new function, replaces get_path_commands()
      Remove obsolete test
      Add tests for PathBuilder
      Path: use a more compact representation
      PathBuilder: Use map().sum() instead of fold()
      PathBuilder: re-slice directly, not with .get().unwrap()
      (#129): Fix baseline-shift for simple subscripts/superscripts and absolute offsets
      (#548): Support images with data: URLs that don't have a MIME-type
      (#578): Link the C tests to harfbuzz so they can call hb_version_string()
      (#582) - Parse XML processing instructions with xml5ever so we can build on Rust 1.39
      (#584): Fix arithmetic overflow when requesting large pixbufs
      (#581): Don't call g_warning and g_critical from the C code
      Move rsvg_g_warning and rsvg_g_critical to messages.rs
      Implement rsvg_return_if_fail / rsvg_return_val_if_fail in Rust
      Minor fix to the documentation of rsvg_pixbuf_from_file_at_size
      Do all simple argument checks in Rust
      Do all the GType checks for the C API in the Rust code
      Use a single rsvg_rust_handle_set_dpi_x_y
      Remove unused functions
      (#588) - Fix panic when a big viewBox does creates an invalid transform
      Fix obsolete comment
      (#592): Fix invalid argument to g_log_structured_array()
      transform_rect() - Avoid an allocation and simplify the loop a bit
      (#594): Only compute locale info for elements that need it.
      (#590): Fix regression when rendering masks
      Oops, add rsvg_handle_set_stylesheet to the gtk-docs.
      Svg::get_size - Don't convert the size to ints
      rsvg_rust_handle_get_dimensions: log errors just like in get_dimensions_sub
      Combine the get_dimensions and get_dimensions_sub implementations into a single function
      rsvg_rust_handle_get_dimensions - use get_dimensions_sub internally
      Fix internal call to get_dimensions_sub
      Move the implementation of render_cairo_sub to c_api
      Remove superfluous casts
      pixbuf_utils: don't call get_dimensions_sub twice.
      rsvg_internals: export the Rect type along with IRect
      pixbuf_utils: get rid of RsvgDimensionData as early as possible
      pixbuf_utils: Use get_geometry_sub instead of get_dimensions_sub
      Move the implementation of get_dimensions_sub to c_api
      Move the implementation of get_position_sub to c_api
      Use the cast crate for checked casts from f64 to i32
      pixbuf_utils: Maintain the original document size as f64
      pixbuf_utils: Use f64 everywhere except at the very end, and check the f64 to i32 conversion
      Test that files with big viewBox don't overflow the dimensions API
      Test that the pixbuf API doesn't overflow
      BoundingBox: new functions rect_is_empty / ink_rect_is_empty
      generate_cairo_mask: Don't push the mask_cr for longer than needed
      generate_cairo_mask - Create the bounding box transform as per the rest of the code
      Rename Transform::new to new_unchecked
      DrawingCtx::clip_to_node - Prepare for switching to BoundingBox::rect_to_transform
      clip_to_node - Use a new function BoundingBox.rect_to_transform
      gradient: use bbox.rect_to_transform instead of checking the rect by hand
      (#593): Don't panic with an empty objectBoundingBox for a mask
      Remove obsolete comment
      Add doc comment to DrawingCtx.push_new_viewport
      Move RsvgDimensionData to c_api
      Move RsvgPositionData to c_api
      Move the size_callback machinery to c_api
      First try at documenting LoadingError
      First try at documenting RenderingError
      Document ViewBox
      Document DefsLookupErrorKind
      Document the Handle struct
      Improve the public docs of IntrinsicDimensions
      Move the default DPI machinery to c_api
      rsvg_internals::Dpi - Make the x/y fields public and remove the accessor functions
      ViewParams: use a Dpi field, not separate dpi_x/dpi_y ones
      (#596): Fix introspection data for rsvg_handle_set_stylesheet()
      cargo fmt
      Reminder to keep cairo-rs versions in sync
      Add a couple of serif fonts for the test suite
      Add test files for #577 - ensure font-family works with multiple families
      Ensure that font-family="quoted  with  multiple  spaces'" preserves the spaces
      Update criterion to 0.3 and the benchmarks to Rust 2018
      Add a benchmark for pixbuf_from_surface
      Use the rgb crate and define a CairoARGB pixel type
      Implement a Rows iterator for SharedImageSurface, yields &[CairoARGB]
      Use the rows iterator in pixbuf_from_surface to iterate the SharedImageSurface
      Reimplement pixbuf_from_surface() in terms of iterators and .as_pixels()
      Reimplement ExclusiveImageSurface::from_pixbuf() in terms of iterators
      RowsMut: keep a cairo::ImageSurfaceData around so it will mark the surface as dirty when dropped
      Fix Makefile.am for "make distcheck"
      Update NEWS

Gabriel Majeri (2):
      Remove deprecated `description` from error types
      Enable rustc lints and solve them

Hao Guan (1):
      rsvg-convert: Accept RGBA colors for the --background-color option

Kleis Auke Wolthuizen (1):
      Improve lib name workaround for Rust *-pc-windows-gnu targets

Paolo Borelli (49):
      css: use the is_element utility method
      node: add and use a is_chars method
      css: simplify is_empty
      text: remove usage of NodeType::Chars
      node: remove NodeData::get_type()
      node: rename NodeType to ElementType
      element: move element code to its own module
      error: rename NodeError to ElementError
      text: rename NodeChars to Chars
      node: rename RsvgNode to simply Node
      element: rename NodeTrait to ElementTrait
      element: set the correct SpecifiedValues at creation
      svg: do not use the parent param in set_atts
      element: remove dedicated is_overflow getter
      Add a user agent stylesheet
      properties: do not override presentation attributes for ua.css
      Fix links in the documentation intro
      Fix link in the documentation
      filters: move unit check at rendering time
      element: remove parent argument from set_atts
      element: set the atts directly in the create fn
      element: simply get the locale from the env
      element: inline set_atts in the create function
      element: provide default empty set_atts
      element: add Element::draw()
      element: add Element::as_filter_effect()
      element: encapsluate access to element_impl
      node: fix comment
      document: make function private
      element: move is_accessed_by_reference method
      node: delegate display trait to element
      gradient: simplify macro
      drawing_ctx: use early return for readability
      xml: use more idiomatic rust
      document: rework acquire()
      Remove oudated comment
      Move CustomIdent to the parsers module
      Rework element representation
      marker: remove special casing of display property
      element: Split ElementTrait in two traits, SetAttributes and Draw
      element: implement the traits also for Element and ElementInner
      element: replace create_element function with Element::new
      filter: shorten code
      use: shorten code
      node: fix comment
      image: fix clippy warning
      lighting: simplify code structure
      Format
      element: get Locale only once

Sergey "Shnatsel" Davidoff (2):
      Swap SmallVec for TinyVec
      Switch Default impl for PathCommand to an all-zeroes bit pattern

Sven Neumann (22):
      tests: Add infrastructure to test the rust-convert command-line tool
      tests: Fix CI run where srcdir != builddir
      tests: Add test for rsvg-convert --help
      tests: Add predicate to check the size of the generated PNG
      tests: Add tests for rsvg-convert output size options
      tests: List more rsvg-convert features that should be tested
      tests: Add tests for rsvg-convert resolution options
      tests: Add tests for other output formats of rsvg-convert
      tests: Use existing SVG for rsvg-convert size tests
      tests: Improve PDF tests for rsvg-convert using the lopdf crate
      tests: Add tests for rsvg-convert setting the PDF CreationDate
      tests: Add tests for some more rsvg-convert options
      tests: Add tests for rsvg-convert output option
      rsvg-convert: apply scale once, not again on each output page
      Update lopdf and chrono dependencies
      Remove obsolete workarounds for datetime parsing
      Update the man page for rsvg-convert
      tests: Use more specific variants of g_assert()
      tests: add test to check the size of PDF created by rsvg-convert
      tests: restructure modules for the rsvg-convert test framework
      tests: test the rsvg-convert --keep-aspect-ratio option
      Cargo update

Version 2.49.0

- Memory consumption of parsed SVG data is greatly reduced.  Property
  values, path data, and text nodes now use much less memory than
  before.  Thanks to Sergey "Shnatsel" Davidoff and Adam Reichold for
  their contributions.

- With that reduction in memory consumption, librsvg can now load up
  to 1 million XML elements.  This is a hard limit to avoid malicious
  files consuming arbitrary amounts of memory.

- #508 - radialGradient now supports the "fr" property from SVG2
  (Dunja Lalic, Corentin Rossignon).

- Sven Neumann has written a fantastic test suite for rsvg-convert(1).

(NEWS truncated at 15 lines)