librsvg: Autospec creation for version 2.45.7
Configure with "--enable-vala" to avoid errors such as:

error: Package `librsvg-2.0' not found in specified Vala API directories

when building packages that use "vala" and require "libsvrg".